---
- name: Install requirements
  become: true
  package:
    name:
      - python3-pip
      - python3-virtualenv
      - python3-dev
      - virtualenv
    state: present

- name: Install system packages required for pyenv
  become: true
  when: python3_pyenv != None
  package:
    name:
      - curl
      - gcc
      - git
      - libbz2-dev
      - libreadline-dev
      - libssl-dev
      - libsqlite3-dev
      - make
      - zlib1g-dev
    state: present